version: 2.1
jobs:
  build:
    docker: # Executor タイプです。他に machine、macOS という実行タイプを指定できます
      - image: circleci/node:10 # プライマリコンテナです。このなかでジョブコマンドが実行されます      
    steps:
      - checkout
      - run: npm install typescript
      - sonarcloud/scan
      - run: echo "hello worldx"
      - run: jq --version
      - run:
          command: |
            STATUS=$(curl -u "${SONAR_TOKEN}:" https://sonarcloud.io/api/qualitygates/project_status?projectKey=kura2020_public2020 | jq -r '.projectStatus.status')
            echo "Status of SonarQube task is ${STATUS} "
            if [ "${STATUS}" != "OK" ]; then
                echo "Quality gate is not OK - exiting with error"
                # exit 1
            fi
      - run: 
          command: npm install
          working_directory: ./helloworld-webpart
      - run: 
          name : gulp bundle --ship
          command: |
            echo "export PATH=/home/circleci/project/helloworld-webpart/node_modules/.bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
            gulp bundle --ship
          working_directory: ./helloworld-webpart
      - run: 
          name : gulp package-solution --ship
          command: |
            echo "export PATH=/home/circleci/project/helloworld-webpart/node_modules/.bin:$PATH" >> $BASH_ENV
            source $BASH_ENV
            gulp package-solution --ship
          working_directory: ./helloworld-webpart

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
          
