version: 2.1
jobs:
  build:
    docker: # Executor タイプです。他に machine、macOS という実行タイプを指定できます
      - image: circleci/node:4.8.2 # プライマリコンテナです。このなかでジョブコマンドが実行されます      
    steps:
      - checkout
      - sonarcloud/scan
      - run: echo "hello world"
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0
version: 2.1
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud
          
