version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified

    steps:
      - checkout
      - run: dir
      - run:
         command: curl --version
         shell: cmd.exe

      # install SharePoint and Project Client Object Model libraries
      # https://www.nuget.org/packages/Microsoft.SharePointOnline.CSOM/
      - run: Install-Package -Name Microsoft.SharePointOnline.CSOM -MinimumVersion 16.1.20211.12000
      