version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified

    steps:
      - checkout

      # install SharePoint and Project Client Object Model libraries
      # https://www.nuget.org/packages/Microsoft.SharePointOnline.CSOM/
      #- run: nuget install Microsoft.SharePointOnline.CSOM
      # https://www.powershellgallery.com/packages/SharePointOnline.CSOM/0.1.0
      - run: Install-Module -Name SharePointOnline.CSOM -Force
      - run: Get-Module -Name SharePointOnline.CSOM -ListAvailable | Select Name,Version
      
      # upload files to SharePoint Document Library
      - run:
          command: .\spLibUpload.ps1 -url https://spkuratest.sharepoint.com -library "テスト用ライブラリ" -username kura@spkuratest.onmicrosoft.com -password kkuurraa@20 -path C:\Users\circleci\project\javascript\files
          working_directory: .\javascript\tools

workflows:
  main:
    jobs:
      - build:
          #context: sonarcloud
          filters:
            branches:
              only: test-windows
          