version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build: # name of your job
    executor:
      name: win/default # executor type
      size: "medium" # resource class, can be "medium", "large", "xlarge", "2xlarge", defaults to "medium" if not specified

    steps:
      - checkout

      # SonarCloud
      - run: npm install typescript
      #- sonarcloud/scan
      #- run:
      #    command: |
      #      STATUS=$(curl -u "${SONAR_TOKEN}:" https://sonarcloud.io/api/qualitygates/project_status?projectKey=kura2020_public2020 | jq -r '.projectStatus.status')
      #      Write-Host "Status of SonarQube task is ${STATUS} "
      #      if ("${STATUS}" -ne "OK" ){
      #          Write-Host "Quality gate is not OK - exiting with error"
      #          exit 1
      #      }

      # install SharePoint and Project Client Object Model libraries
      # https://www.powershellgallery.com/packages/SharePointOnline.CSOM/0.1.0
      - run: Install-Module -Name SharePointOnline.CSOM -Force
      - run: Get-Module -Name SharePointOnline.CSOM -ListAvailable | Select Name,Version
      
      # upload files to SharePoint Document Library
      - run: Write-Host $env:USERNAME
      - run:
          command: .\spLibUpload.ps1 -url https://spkuratest.sharepoint.com -library "テスト用ライブラリ" -username ${USERNAME} -password ${PASSWORD} -path C:\Users\circleci\project\javascript\files
          working_directory: .\javascript\tools

workflows:
  main:
    jobs:
      - build:
          #context: sonarcloud
          filters:
            branches:
              only: test-windows
          